version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - ai-network
  elasticsearch:
    build: elk/elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      -  ai-network
  logstash:
    build: elk/logstash/
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    links:
      - elasticsearch
    networks:
      -  ai-network
  kibana:
    build: elk/kibana/
    container_name: kibana
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      -  ai-network
  goku-ecommerce:
    build:
      context: ./application
    image: goku-ecommerce
    ports:
      - "8082:8082"
    expose:
      - 8082
    depends_on:
      - mongodb
      - logstash
    networks:
      -  ai-network
networks:
  ai-network: